/**
 * email.js — Optional daily digest via nodemailer
 *
 * Sends a plaintext summary of the day's trends to EMAIL_TO.
 * Only called if EMAIL_ENABLED=true in .env.
 *
 * Uses any SMTP provider — Gmail, Mailgun, Postmark, etc.
 * For Gmail: use an App Password (not your account password).
 * https://support.google.com/accounts/answer/185833
 */

import nodemailer from 'nodemailer';

export async function sendDailyDigest(trends, newJobsToday) {
  const transporter = nodemailer.createTransport({
    host:   process.env.EMAIL_HOST ?? 'smtp.gmail.com',
    port:   parseInt(process.env.EMAIL_PORT ?? '587', 10),
    secure: false,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const subject = `EU Frontend Market — ${newJobsToday} new jobs today (${trends.total_jobs} total)`;
  const text = buildPlaintext(trends, newJobsToday);
  const html = buildHtml(trends, newJobsToday);

  await transporter.sendMail({
    from:    process.env.EMAIL_USER,
    to:      process.env.EMAIL_TO,
    subject,
    text,
    html,
  });
}

// ── Email body builders ───────────────────────────────────────────────────────

function buildPlaintext(trends, newJobsToday) {
  const lines = [
    `EU Frontend Job Market — Daily Digest`,
    `${new Date().toDateString()} | ${newJobsToday} new jobs today | ${trends.total_jobs} total in corpus`,
    '',
    '── Top 10 skills ──',
    ...trends.top_skills.slice(0, 10).map(
      (s, i) => `${String(i + 1).padStart(2)}. ${s.skill.padEnd(20)} ${s.pct}% (${s.count} jobs)`
    ),
    '',
    '── Work mode split ──',
    ...trends.work_mode_split.map((m) => `  ${m.mode.padEnd(10)} ${m.pct}%`),
    '',
    '── Salary by seniority (EUR/yr) ──',
    ...trends.salary_ranges.map(
      (r) => `  ${r.seniority.padEnd(10)} avg ${fmt(r.avg_min)}–${fmt(r.avg_max)} (${r.count} jobs with salary data)`
    ),
    '',
    '── Top tech stack ──',
    ...trends.stack_trends.slice(0, 8).map(
      (s) => `  ${s.name.padEnd(20)} ${s.pct}%`
    ),
  ];
  return lines.join('\n');
}

function buildHtml(trends, newJobsToday) {
  const skillRows = trends.top_skills.slice(0, 15).map((s) => `
    <tr>
      <td style="padding:6px 12px 6px 0;font-size:14px">${s.skill}</td>
      <td style="padding:6px 0;width:200px">
        <div style="background:#eee;border-radius:4px;height:8px">
          <div style="background:#4f46e5;border-radius:4px;height:8px;width:${s.pct}%"></div>
        </div>
      </td>
      <td style="padding:6px 0 6px 10px;font-size:13px;color:#666">${s.pct}% (${s.count})</td>
    </tr>`).join('');

  const workModeRows = trends.work_mode_split.map((m) => `
    <tr>
      <td style="padding:4px 12px 4px 0;font-size:14px">${m.mode}</td>
      <td style="padding:4px 0;font-size:14px;color:#666">${m.pct}%</td>
    </tr>`).join('');

  const salaryRows = trends.salary_ranges.map((r) => `
    <tr>
      <td style="padding:4px 12px 4px 0;font-size:14px">${r.seniority}</td>
      <td style="padding:4px 0;font-size:14px;color:#666">${fmt(r.avg_min)}–${fmt(r.avg_max)} EUR/yr</td>
      <td style="padding:4px 0 4px 10px;font-size:12px;color:#999">${r.count} data points</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:system-ui,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#111">
  <h1 style="font-size:20px;font-weight:600;margin:0 0 4px">EU Frontend Market</h1>
  <p style="color:#666;font-size:14px;margin:0 0 24px">
    ${new Date().toDateString()} &bull; ${newJobsToday} new jobs today &bull; ${trends.total_jobs} total collected
  </p>

  <h2 style="font-size:15px;font-weight:600;border-bottom:1px solid #eee;padding-bottom:8px;margin:0 0 12px">Top skills by frequency</h2>
  <table style="width:100%;border-collapse:collapse">${skillRows}</table>

  <h2 style="font-size:15px;font-weight:600;border-bottom:1px solid #eee;padding-bottom:8px;margin:24px 0 12px">Work mode split</h2>
  <table style="border-collapse:collapse">${workModeRows}</table>

  <h2 style="font-size:15px;font-weight:600;border-bottom:1px solid #eee;padding-bottom:8px;margin:24px 0 12px">Salary by seniority</h2>
  <table style="border-collapse:collapse">${salaryRows}</table>

  <p style="color:#999;font-size:12px;margin:32px 0 0">Generated by eu-job-intel-agent</p>
</body>
</html>`;
}

function fmt(n) {
  if (!n) return '?';
  return `€${Math.round(n / 1000)}k`;
}
